import re
from typing import Dict, List, Set


TECH_DOMAIN_SKILLS: Dict[str, List[str]] = {
    "computer_science": [
        "python",
        "java",
        "c",
        "c++",
        "c#",
        "javascript",
        "typescript",
        "go",
        "rust",
        "php",
        "ruby",
        "sql",
        "nosql",
        "mongodb",
        "postgresql",
        "mysql",
        "redis",
        "api development",
        "microservices",
        "system design",
        "software engineering",
        "software development",
        "object oriented programming",
        "data structures",
        "algorithms",
        "version control",
        "git",
        "linux",
        "docker",
        "kubernetes",
        "aws",
        "azure",
        "gcp",
        "devops",
        "ci cd",
        "unit testing",
        "streamlit",
        "flask",
        "django",
        "react",
        "node.js",
        "html",
        "css",
    ],
    "data_ai": [
        "data science",
        "data analysis",
        "data analytics",
        "data visualization",
        "business intelligence",
        "tableau",
        "power bi",
        "statistics",
        "hypothesis testing",
        "machine learning",
        "deep learning",
        "natural language processing",
        "computer vision",
        "time series forecasting",
        "feature engineering",
        "model evaluation",
        "scikit-learn",
        "tensorflow",
        "pytorch",
        "xgboost",
        "lightgbm",
        "mlops",
        "predictive modeling",
        "a b testing",
        "data mining",
        "etl",
        "spark",
        "hadoop",
        "big data",
        "rag",
        "faiss",
        "transformers",
        "llm",
        "prompt engineering",
    ],
    "biology_life_sciences": [
        "biology",
        "molecular biology",
        "cell biology",
        "microbiology",
        "genetics",
        "genomics",
        "bioinformatics",
        "biostatistics",
        "immunology",
        "biochemistry",
        "ecology",
        "evolutionary biology",
        "zoology",
        "botany",
        "biotechnology",
        "laboratory techniques",
        "gel electrophoresis",
        "pcr",
        "dna sequencing",
        "crispr",
        "scientific writing",
        "experimental design",
    ],
    "medical_healthcare": [
        "medicine",
        "patient care",
        "clinical diagnosis",
        "clinical documentation",
        "electronic health records",
        "medical coding",
        "medical billing",
        "pharmacology",
        "pathology",
        "radiology",
        "anatomy",
        "physiology",
        "public health",
        "epidemiology",
        "clinical research",
        "clinical trials",
        "nursing",
        "emergency medicine",
        "icu care",
        "infection control",
        "healthcare compliance",
        "telemedicine",
    ],
    "pharma_chemistry": [
        "pharmaceutical sciences",
        "drug discovery",
        "drug safety",
        "pharmacovigilance",
        "medicinal chemistry",
        "analytical chemistry",
        "organic chemistry",
        "inorganic chemistry",
        "physical chemistry",
        "quality control",
        "quality assurance",
        "good laboratory practice",
        "good manufacturing practice",
        "regulatory affairs",
        "hplc",
        "gc ms",
        "spectroscopy",
        "formulation development",
    ],
    "finance_accounting": [
        "accounting",
        "financial accounting",
        "managerial accounting",
        "cost accounting",
        "bookkeeping",
        "taxation",
        "auditing",
        "financial reporting",
        "financial modeling",
        "budgeting",
        "forecasting",
        "cash flow analysis",
        "balance sheet",
        "income statement",
        "gaap",
        "ifrs",
        "quickbooks",
        "tally",
        "excel",
        "risk management",
        "investment analysis",
        "equity research",
    ],
    "business_management": [
        "business analysis",
        "market research",
        "strategy",
        "operations management",
        "supply chain",
        "procurement",
        "project management",
        "agile",
        "scrum",
        "stakeholder management",
        "kpi tracking",
        "process improvement",
        "lean",
        "six sigma",
        "customer relationship management",
        "crm",
        "erp",
    ],
    "marketing_sales": [
        "digital marketing",
        "content marketing",
        "social media marketing",
        "seo",
        "sem",
        "performance marketing",
        "email marketing",
        "brand management",
        "product marketing",
        "copywriting",
        "sales strategy",
        "lead generation",
        "sales forecasting",
        "account management",
        "customer success",
        "google analytics",
        "meta ads",
    ],
    "design_creative": [
        "graphic design",
        "ui design",
        "ux design",
        "ui ux",
        "interaction design",
        "product design",
        "wireframing",
        "prototyping",
        "user research",
        "usability testing",
        "figma",
        "adobe xd",
        "photoshop",
        "illustrator",
        "indesign",
        "motion graphics",
        "video editing",
        "branding",
        "typography",
    ],
    "architecture_civil": [
        "architecture",
        "architectural design",
        "interior design",
        "urban planning",
        "landscape design",
        "autocad",
        "revit",
        "bim",
        "sketchup",
        "construction management",
        "structural analysis",
        "building codes",
        "quantity surveying",
        "estimation",
        "civil engineering",
        "surveying",
        "geotechnical engineering",
        "transportation engineering",
        "water resources engineering",
        "gis",
    ],
    "mechanical_manufacturing": [
        "mechanical engineering",
        "manufacturing engineering",
        "thermodynamics",
        "fluid mechanics",
        "heat transfer",
        "cad",
        "cam",
        "solidworks",
        "catia",
        "ansys",
        "finite element analysis",
        "cnc machining",
        "lean manufacturing",
        "quality engineering",
        "industrial engineering",
        "automation",
        "robotics",
    ],
    "electrical_electronics": [
        "electrical engineering",
        "electronics",
        "circuit design",
        "power systems",
        "power electronics",
        "control systems",
        "embedded systems",
        "microcontrollers",
        "vlsi",
        "verilog",
        "fpga",
        "signal processing",
        "iot",
        "pcb design",
        "matlab",
        "simulink",
    ],
    "law_policy": [
        "legal research",
        "contract drafting",
        "compliance",
        "corporate law",
        "intellectual property",
        "litigation",
        "policy analysis",
        "regulatory compliance",
        "documentation",
        "case analysis",
    ],
    "education_research": [
        "teaching",
        "curriculum design",
        "instructional design",
        "assessment design",
        "classroom management",
        "mentoring",
        "academic research",
        "research methodology",
        "data interpretation",
        "publication writing",
    ],
    "hospitality_tourism": [
        "hospitality management",
        "hotel operations",
        "front office operations",
        "food and beverage service",
        "event management",
        "travel planning",
        "guest relations",
        "reservation systems",
    ],
    "agriculture_environment": [
        "agriculture",
        "agronomy",
        "soil science",
        "horticulture",
        "plant pathology",
        "sustainable farming",
        "environmental science",
        "environmental impact assessment",
        "waste management",
        "climate analysis",
        "remote sensing",
    ],
    "media_communication": [
        "journalism",
        "content writing",
        "technical writing",
        "public relations",
        "broadcast media",
        "script writing",
        "editing",
        "storytelling",
        "communication strategy",
    ],
}

SOFT_SKILLS: List[str] = [
    "communication",
    "leadership",
    "problem solving",
    "critical thinking",
    "collaboration",
    "teamwork",
    "time management",
    "adaptability",
    "decision making",
    "attention to detail",
    "negotiation",
    "presentation skills",
    "analytical thinking",
    "creativity",
    "conflict resolution",
]

SKILL_ALIASES: Dict[str, str] = {
    "ai": "artificial intelligence",
    "ml": "machine learning",
    "nlp": "natural language processing",
    "cv": "computer vision",
    "ds": "data science",
    "data scientist": "data science",
    "data scientists": "data science",
    "datascience": "data science",
    "bi": "business intelligence",
    "powerbi": "power bi",
    "node": "node.js",
    "nodejs": "node.js",
    "js": "javascript",
    "ts": "typescript",
    "oop": "object oriented programming",
    "ci/cd": "ci cd",
    "uiux": "ui ux",
    "uxui": "ui ux",
    "ehr": "electronic health records",
    "emr": "electronic health records",
    "icu": "icu care",
    "gmp": "good manufacturing practice",
    "glp": "good laboratory practice",
    "qa": "quality assurance",
    "qc": "quality control",
    "fea": "finite element analysis",
    "pm": "project management",
    "crm": "customer relationship management",
}


def _dedupe(items: List[str]) -> List[str]:
    out: List[str] = []
    seen: Set[str] = set()
    for item in items:
        skill = re.sub(r"\s+", " ", item.strip().lower())
        if skill and skill not in seen:
            out.append(skill)
            seen.add(skill)
    return out


TECH_SKILLS: List[str] = _dedupe([s for values in TECH_DOMAIN_SKILLS.values() for s in values])


def _compile_term_pattern(term: str) -> re.Pattern:
    escaped = re.escape(term.lower().strip())
    escaped = escaped.replace(r"\ ", r"\s+")
    return re.compile(rf"(?<![a-z0-9]){escaped}(?![a-z0-9])")


TECH_PATTERNS: Dict[str, re.Pattern] = {skill: _compile_term_pattern(skill) for skill in TECH_SKILLS}
SOFT_PATTERNS: Dict[str, re.Pattern] = {skill: _compile_term_pattern(skill) for skill in SOFT_SKILLS}
ALIAS_PATTERNS: Dict[str, re.Pattern] = {alias: _compile_term_pattern(alias) for alias in SKILL_ALIASES}


def _normalize(text: str) -> str:
    return re.sub(r"\s+", " ", (text or "").lower()).strip()


def extract_tech_skills(text: str) -> List[str]:
    text_l = _normalize(text)
    if not text_l:
        return []

    matched: Set[str] = set()
    for skill, pattern in TECH_PATTERNS.items():
        if pattern.search(text_l):
            matched.add(skill)

    for alias, canonical in SKILL_ALIASES.items():
        if ALIAS_PATTERNS[alias].search(text_l):
            matched.add(canonical)

    return sorted(matched)


def extract_soft_skills(text: str) -> List[str]:
    text_l = _normalize(text)
    if not text_l:
        return []

    matched = [skill for skill, pattern in SOFT_PATTERNS.items() if pattern.search(text_l)]
    return sorted(set(matched))
